### PR TITLE
DatePicker: expose msg types

### PR DESCRIPTION
**Pull request by dzyp**
This is really helpful if you have a form and you want to autopopulate a date field based on the selection in some other date field.

### CODE REVIEW

**Comment by Bogdanp** [comment]
What's stopping you from doing this currently?

```elm
update msg model = 
  case msg of 
    DateSelected date ->
      let 
        settings = { defaultSettings | pickedDate = Just date }
        (datePicker, datePickerCmds) = DatePicker.init settings
      in
        { model | datePicker = datePicker } ! [ datePickerCmds ]
```

I'm hesitant to expose those constructors without some example showing that the thing you're trying to do isn't feasible using the current API.

**Comment by bbqbaron** [comment]
Closing just for tidiness, since the original question seems to have gone unanswered. Please feel free to reopen if you need to.

**Comment by michaeljones** [comment]
I'd like to see this in the readme as I struggled to understand how one my set the date on a date picker. Might be obvious to those more familiar with elm but I guess I'm not quite there yet :)

I was looking through the code and trying to use `setDate`. It did not occur to me that re-initialising would be a pattern, though I can see why it is in hindsight.

**Comment by bbqbaron** [comment]
By all means! That would be very welcome.

**Pull request closed without merging**
