### PR TITLE
Fix yearRange bug, when building From range to todays date

### LINKED ISSUE #76: When changeYear is active, changing year causes that year to be set to the top of the range
To reproduce:

Initialise dp with default settings, apply the *from* function to the changeYear field to set a [date up until the current date](http://package.elm-lang.org/packages/elm-community/elm-datepicker/latest/DatePicker#from)

```elm
  { defaultSettings  | changeYear = DatePicker.from 1950 }
```
After initialising DatePickers update & view functions, change selected year from 2018 to 2017-
image
image
image

Now click on the year select menu again...

image
Notice the last available year to select is 2017. 

This issue persists when attempting to change to lower years after.  

Hope to resolve as this is awesome otherwise :)

### PR DESCRIPTION
**Pull request by njsfield**
Fixes #76

### CODE REVIEW

**Comment by bbqbaron** [comment]
Thanks for the PR! Not having implemented this feature, I'm basing this on reading the code, but: doesn't it seem like `focused` shouldn't be passed at all? It looks like the `To` case would have the same bug, but in reverse, constantly pushing the beginning of the year range forward to `focused` each time. Should we just use `today` for `To` as well and eliminate `focused` entirely?

(This is triggering one of those "How did that ever work?" moments, y'know?)

What do you think? Too much scope creep?

**Comment by njsfield** [comment]
Very much agreed! The To case indeed had the same issue, so I've updated my PR to allow yearRange to specify the 'today' date to build a list from. 

I also noticed the MoreOrLess generated year-list was using currentMonth build a surrounding list of dates. I didn't think this was the expected functionality either, as currentMonth relates to focused date (so selecting a different year would result in a year-range surrounding the new year). I've updated this function to generated a MoreOrLess range around todays date too, so now the yearRange function only needs to accept a single anchor date (today) and a YearRange

**Comment by bbqbaron** [comment]
Thanks! I see what you mean about `MoreOrLess`. I'm on the fence about it, since unlike `From` and `To`, the current behavior doesn't result in years becoming outright unreachable, although I agree that it acts somewhat strangely. I think we should be conservative for the sake of API stability and preserve its current behavior. If someone wants a range relative to today, they can always use `Between`, right? Mind reverting it?

**Comment by njsfield** [comment]
Yeah, I'm undecided...
A scenario where I imagined it could be problematic would perhaps be;
1) Developer needs Datepicker to allow users to users to choose a Date some number of years before/after X. Perhaps they need to initialise Datepicker with a specific (non-today) Date too. For business logic reasons users should be prevented from selecting a date outside of this range.
2) User sees the year range, selects a year in the lower range.
3) User then changes their mind, goes to select another year and is presented with a different range of years.
4) User selects a year out of the original date range, then attempts to submit a form (and server throws error etc)

Happy to be conservative for the API though and raise this as a separate issue 👍 I've reverted the PR as requested

**Pull request merged**
