### PR TITLE
created locate_pt_br

### PR DESCRIPTION
**Pull request by Bernardoow**
Hi community !!

I am sharing my locate pt.

I give my suggestion to community to create a locale folder to add future translations that will be added.

### CODE REVIEW

**Comment by bbqbaron** [comment]
Thanks for the PR. I'm looking at the PT_BR locale inside [elm-date-extra](https://github.com/rluiten/elm-date-extra/blob/master/src/Date/Extra/I18n/I_pt_br.elm) and it looks like this code does something very similar. It seems like the program should just use `Date.Extra.I18n` to format, and this package to provide UI. Does that sound reasonable? Is there some part of that that is difficult or a bad idea?

**Comment by bbqbaron** [comment]
Closing, since hopefully my suggestion was helpful!

**Comment by Bernardoow** [comment]
Oh, sorry. I just saw this topic now.
Yes your suggestion is great.
Maybe you should describe this tip in documation.

**Comment by Bernardoow** [comment]
@bbqbaron

I needed to stop the project that was and this week I developed again.
Today I implemented the part for i18n and together with my team we decided not to use the lib you held for reasons: we did not need anything else, we do not know if the maintainer will continue updating the lib for new versions of ELM.

**Pull request closed without merging**
