### PR TITLE
Provide a usage run through in the README

### PR DESCRIPTION
**Pull request by michaeljones**
To help people who are newer to elm and unsure of how to interact with libraries. In particular I wanted to cover the 'how to upate a date picker' case which is achieved by creating a new date picker with the
new date which isn't necessarily a pattern that beginner's will think of.

Happy to hear feedback if it can be improved. I am somewhat of a beginner!

### CODE REVIEW

**Comment by michaeljones** [comment]
Force pushed with a small typo fixed. `s/mode/model/`

**Comment by bbqbaron** [comment]
A docs PR! My favorite kind. What do you think of _only_ including the example of how to alter the date by just providing a new picker, or perhaps changing the instructions on merely using the picker to a link to the Elm docs? Here's my reasoning: The general this-is-a-component part before that seems mostly to be explaining how to integrate any good Elm-architecture component into your app. Although that's definitely useful, it feels like docs should be fairly specific to their libraries. Thoughts? Too obtuse?

**Comment by michaeljones** [comment]
Hey, thanks for the response. I was inspired by the [RemoteData docs](http://package.elm-lang.org/packages/krisajenkins/remotedata/4.3.0/RemoteData) which kind of hold your hand through the whole process pretty well. I think having more documentation is basically always good. I don't feel that there is harm in over explaining something. More experienced users can skim over it pretty easily and beginners have a much better experience if this is one of the first libraries they are encountering. There is a [r/elm](https://www.reddit.com/r/elm/comments/5vh1fi/where_do_you_suffer_most_while_programming_in_elm/) thread in which minimalist documentation is raised as a concern and I share it. Minimalist documentation can feel quite cold & unfriendly. 

I recognise that having more documentation is potentially more of a burden on you as a project maintainer. More to update if anything changes, but I do not feel that this is an unnecessarily large amount of documentation. 

All that said, I do see your point that it is essentially explaining stuff that should be clear to someone familiar with elm. Happy if you do decide to cut it down.

Finally, thanks for running the project. I'm using elm at work for the first time and it was a relief to find a datepicker that could be plugged in nice & easily.

**Comment by bbqbaron** [comment]
> Finally, thanks for running the project. I'm using elm at work for the first time and it was a relief to find a datepicker that could be plugged in nice & easily.

No problem, although I took it over from another and can't claim credit for its existence :|.

Anyway, I think I'm convinced that you're right. You've certainly cited sources, and I probably am too impatient with docs. Merging and thanks again.

**Pull request merged**
