### PR TITLE
make sure that the selected month is also adjusted when we use setDate

### PR DESCRIPTION
**Pull request by julianjelfs**
Without this change, when you call setDate to specify a date that is not currently visible, the next time you open the date picker you will have to navigate to the selected date. Seems like this is unlikely to be the expected / desired behaviour.

### CODE REVIEW

**Comment by bbqbaron** [comment]
Sheesh, thanks for catching this.

I think this problem is a symptom of a structural issue: should `prepareDates` ever _not_ be called? Looking at the code, the only time we don't `prepareDates` is when we happen to know that the given action hasn't resulted in a date change...and that's why this is broken, no? What if update were just `mapModel prepareDates << update`?

**Comment by julianjelfs** [comment]
Well is it a problem with the update function or is it the fact that when setDate is called the undate function is not getting called at all. It seems to me now that setDate is just an explicitly triggered Msg (i.e. Pick), so we could change setDate so that it just calls update with a Pick Msg:

```
setDate : Date -> DatePicker -> DatePicker
setDate date picker =
    let
        ( updatedPicker, _, _ ) =
            update (Pick date) picker
    in
        updatedPicker
``` 
The up side to that is that the actual update logic stays in the right place, in the update function. The downside is that we are throwing away any Cmd that the Pick msg might generate. Currently it doesn't generate any but it feels dodgy to not return it given that in the future it may return something. 

I would be perfectly happy with the above, or with changing the return type of setDate so that it returns a Tuple that includes the Cmd (for future proofing). 

What do you think? 

PS - I'm happy to make the changes

**Comment by bbqbaron** [comment]
Oh, right, sorry; I was plowing through PRs and didn't even think that `setDate` isn't in `update`. Gross.

What if we just expose a `Msg` tag wrapper `pick` that's just `Pick`, in the usual way of Elm constructor-helpers? Then you, the user of `DatePicker`, just call `update (pick date)` yourself? Then we don't have to establish new patterns around model-mutators-that-aren't-updaters and how they should be expected to work.

**Comment by julianjelfs** [comment]
Yes I think I like that. Would you propose removing setDate as well? Only reason not too I think would be backward compatibility?

**Comment by bbqbaron** [comment]
I would definitely recommend removing it. Since there's a major bump incoming from a set of recent PRs, I figure we just remove it and make a note that it can easily be replaced by `update (pick data) model.datePicker >> Tuple.first` or something like that.

**Comment by julianjelfs** [comment]
Sure, ok. Would you like me to have a go at that change and raise another PR?

**Comment by bbqbaron** [comment]
By all means have at it! I think we can reuse this PR for it, though, if you're not worried it'll muddle the compare. Thanks for doing this!

**Comment by julianjelfs** [comment]
OK I think that's done. Tried it locally and works fine.

**Comment by bbqbaron** [comment]
Wow, the PR ended up really elegant! Always a good feeling when we don't have to do acrobatics to improve something. Thanks so much and sorry for the long initial wait. I'll merge this.

There'll be a documentation pass before release, what with a few merges happening at once; I'll make sure  to explain this option.

**Pull request merged**
